spring.application.name=PostMain-FyneOn
# Redis User
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Redis Post
custom.redis-usercache.host=localhost
custom.redis-usercache.port=6380

# ========== Kafka Consumer ==========
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=post-service-group
spring.kafka.consumer.auto-offset-reset=earliest
# ?????????????? ? ?????????? ??????
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer






server.port=7070